name: Deploy to Heroku from develop

on:
  push:
    branches:
      - develop # Changing the branch here would also work

jobs:
  build:
    name: Heroku Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "notifai-textify" #Must be unique in Heroku
          heroku_email: "maciej.budzynski@spoko.pl"
          branch: "develop"
